# Generated by Django 2.1.2 on 2018-10-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('ref_id', 'vendor')},
        ),
    ]
