# Generated by Django 2.1.2 on 2018-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='SCHEDULED', max_length=16),
        ),
    ]
