# Generated by Django 2.1.2 on 2018-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181027_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='key',
        ),
        migrations.AddField(
            model_name='notification',
            name='tracking_key',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='app_login_key',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
