# Generated by Django 2.1.2 on 2018-11-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181115_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='start_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='spatialdistance',
            unique_together={('origin', 'destination')},
        ),
    ]
