# Generated by Django 2.1.2 on 2018-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181118_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialdistance',
            name='value',
            field=models.FloatField(),
        ),
    ]
